import { registerAs } from '@nestjs/config';
import { validateEnvironment } from './env';

export default registerAs('app', () => {
  const env = validateEnvironment(process.env);
  return {
    botToken: env.BOT_TOKEN,
    nodeEnv: env.NODE_ENV,
    logLevel: env.LOG_LEVEL,
    port: env.PORT,
    paymentProvider: env.PAYMENT_PROVIDER,
    remnawave: {
      apiUrl: env.REMNAWAVE_API_URL,
      apiToken: env.REMNAWAVE_API_TOKEN,
      internalSquadUuid: env.REMNAWAVE_INTERNAL_SQUAD_UUID,
      timeoutMs: env.REMNAWAVE_TIMEOUT_MS,
    },
    fulfillment: {
      workerEnabled: env.FULFILLMENT_WORKER_ENABLED,
      retryDelaysMs: env.FULFILLMENT_RETRY_DELAYS_MS.split(',').map(Number),
    },
    mtproto: {
      apiUrl: env.MTPROTO_INTERNAL_API_URL,
      apiKey: env.MTPROTO_INTERNAL_API_KEY,
      timeoutMs: env.MTPROTO_INTERNAL_API_TIMEOUT_MS,
      targetHost: env.MTPROTO_TARGET_HOST,
      sshUser: env.MTPROTO_SSH_USER,
      sshMtUser: env.MTPROTO_SSH_MT_USER,
      sshKeyPath: env.MTPROTO_SSH_PRIVATE_KEY_PATH,
      sshPort: env.MTPROTO_SSH_PORT,
      sshConnectTimeout: env.MTPROTO_SSH_CONNECT_TIMEOUT,
      sshCommandTimeout: env.MTPROTO_SSH_COMMAND_TIMEOUT,
      sshControlPersist: env.MTPROTO_SSH_CONTROL_PERSIST,
      sshControlPathDir: env.MTPROTO_SSH_CONTROL_PATH_DIR,
      containerName: env.MTG_CONTAINER_NAME,
      mtgPort: env.MTG_PORT,
      configPath: env.MTG_CONFIG_PATH,
      dockerImage: env.MTG_DOCKER_IMAGE,
      providerCommandTimeoutS: env.MTPROTO_PROVIDER_COMMAND_TIMEOUT_S,
      backupDir: env.MTPROTO_BACKUP_DIR,
      backupRetentionCount: env.MTPROTO_BACKUP_RETENTION_COUNT,
      scannerBinaryPath: env.SCANNER_BINARY_PATH,
      scannerWorkDir: env.SCANNER_WORK_DIR,
      scannerWhitelist: env.SCANNER_WHITELIST,
      scannerThreadCount: env.SCANNER_THREAD_COUNT,
      scannerPerHostTimeoutS: env.SCANNER_PER_HOST_TIMEOUT_S,
      scannerCommandTimeoutS: env.SCANNER_COMMAND_TIMEOUT_S,
      healthCheckRetries: env.HEALTH_CHECK_RETRIES,
      healthCheckRetryDelayMs: env.HEALTH_CHECK_RETRY_DELAY_MS,
      healthCheckTimeoutS: env.HEALTH_CHECK_TIMEOUT_S,
      selectorAllowedCountries: env.SELECTOR_ALLOWED_COUNTRIES,
      selectorBlockedIssuers: env.SELECTOR_BLOCKED_ISSUERS,
      accessHost: env.MTPROTO_ACCESS_HOST,
      accessUser: env.MTPROTO_ACCESS_USER,
      accessKeyPath: env.MTPROTO_ACCESS_SSH_PRIVATE_KEY_PATH,
      accessPort: env.MTPROTO_ACCESS_SSH_PORT,
      accessPath: env.MTPROTO_ACCESS_PATH,
      publicHost: env.MTPROTO_ACCESS_PUBLIC_HOST,
      lumintoCacheTtlMs: env.MTPROTO_LUMINTO_CACHE_TTL_MS,
    },
    llm: {
      priorityChain: env.LLM_PRIORITY_CHAIN.split(',').map((id) => id.trim()),
      retryCount: env.LLM_RETRY_COUNT,
      retryDelayMs: env.LLM_RETRY_DELAY_MS,
      healthFailureThreshold: env.LLM_HEALTH_FAILURE_THRESHOLD,
      healthCooldownMs: env.LLM_HEALTH_COOLDOWN_MS,
      requestTimeoutMs: env.LLM_REQUEST_TIMEOUT_MS,
      providers: {
        gemini: { apiKey: env.GEMINI_API_KEY, model: env.GEMINI_MODEL },
        groq: { apiKey: env.GROQ_API_KEY, model: env.GROQ_MODEL, baseUrl: env.GROQ_BASE_URL },
        openrouter: { apiKey: env.OPENROUTER_API_KEY, model: env.OPENROUTER_MODEL, baseUrl: env.OPENROUTER_BASE_URL },
        cerebras: { apiKey: env.CEREBRAS_API_KEY, model: env.CEREBRAS_MODEL, baseUrl: env.CEREBRAS_BASE_URL },
        nvidia: { apiKey: env.NVIDIA_API_KEY, model: env.NVIDIA_MODEL, baseUrl: env.NVIDIA_BASE_URL },
      },
    },
  };
});
